GCC 11.1.0 task_struct member name reference fix
In GCC 11.1.0 an error occurs on when making the vmmon module on Linux 5.14.0. This is due to a member reference issue on line 478, 2583, 2590, and 2672. This prevents the building of the module. The minor line changes fixes the reference and allows this module to complies properly. 

The error I got is below:
make[1]: Entering directory '/usr/lib/modules/5.14.0-0/build'
  CC [M]  /usr/lib/vmware/modules/source/vmmon-only/linux/hostif.o
/usr/lib/vmware/modules/source/vmmon-only/linux/hostif.c: In function ‘HostIF_WakeUpYielders’:
/usr/lib/vmware/modules/source/vmmon-only/linux/hostif.c:478:20: error: ‘struct task_struct’ has no member named ‘state’; did you mean ‘__state’?
  478 |       if (t && (t->state & TASK_INTERRUPTIBLE)) {
      |                    ^~~~~
      |                    __state
/usr/lib/vmware/modules/source/vmmon-only/linux/hostif.c: In function ‘HostIF_SemaphoreWait’:
/usr/lib/vmware/modules/source/vmmon-only/linux/hostif.c:2583:13: error: ‘struct task_struct’ has no member named ‘state’; did you mean ‘__state’?
 2583 |    current->state = TASK_INTERRUPTIBLE;
      |             ^~~~~
      |             __state
/usr/lib/vmware/modules/source/vmmon-only/linux/hostif.c:2590:13: error: ‘struct task_struct’ has no member named ‘state’; did you mean ‘__state’?
 2590 |    current->state = TASK_RUNNING;
      |             ^~~~~
      |             __state
/usr/lib/vmware/modules/source/vmmon-only/linux/hostif.c: In function ‘HostIF_SemaphoreForceWakeup’:
/usr/lib/vmware/modules/source/vmmon-only/linux/hostif.c:2672:20: error: ‘struct task_struct’ has no member named ‘state’; did you mean ‘__state’?
 2672 |       if (t && (t->state & TASK_INTERRUPTIBLE)) {
      |                    ^~~~~
      |                    __state
make[2]: *** [scripts/Makefile.build:271: /usr/lib/vmware/modules/source/vmmon-only/linux/hostif.o] Error 1
make[1]: *** [Makefile:1851: /usr/lib/vmware/modules/source/vmmon-only] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.14.0-0/build'
make: *** [Makefile:117: vmmon.ko] Error 2